### ISSUE TITLE
ds_append 命令错误操作

### ISSUE THREAD

**Issue by LazyZhu** [qiye/redis-storage#13]
```
ds_set mykey "Hello"
ds_append mykey " World"
ds_get mykey
```

返回的不应该是`Hellomykey`，而应该是`Hello World`
另外`ds_append`返回的不应该是OK，而应该是被append后总长度

**Comment by shenzhe** [comment]
一些命令的返回值确实会不一致，我在我的分支会跟进一下。
到时再统一pull到主库。

**Comment by qiye** [comment]
嗯。昨晚已经修复这个问题了。请重新下载 新版

**Comment by LazyZhu** [comment]
@qiye 恩，已修复了 :)

还有希望返回值和redis统一下 :)

**Comment by qiye** [comment]
返回值也统一了。刚刚修复的
