### ISSUE TITLE
ds_keys_asc，ds_keys_desc 导致 redis-storage 崩溃

### ISSUE THREAD

**Issue by LazyZhu** [qiye/redis-storage#14]
RT.

http://198.74.110.195/t2
https://gist.github.com/ed560f14576810718c3d

暂时取消了ds_keys_asc ds_keys_desc 命令测试 :)

**Comment by qiye** [comment]
我看看，尽快fix

**Comment by shenzhe** [comment]
@LazyZhu   加入Q群：51804082

**Comment by qiye** [comment]
这两个命令，暂时删除。我会加上 基于key的 遍历查询
