### ISSUE TITLE
编译出错 ds.c

### ISSUE THREAD

**Issue by rchunping** [qiye/redis-storage#6]
void ds_mget(redisClient *c) 中
需要把 这行注释掉
 //              sdsfree(str);

另外linenoise 没有依赖进去，需要先进去make 一下

还有 有些系统上 修改src/Makefile 加上 -lstdc++ -lm

ifeq ($(MALLOC),tcmalloc_minimal)
  FINAL_CFLAGS+= -DUSE_TCMALLOC
  FINAL_LIBS+= ../deps/gperftools-2.0/.libs/libtcmalloc_minimal.a -ldl -lstdc++ -lm
endif

**Comment by shenzhe** [comment]
感谢反馈

**Comment by qiye** [comment]
嗯。已经解决。
